# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node
    steps:
      - checkout
      - run:
          name: 'PHPCS'
          command: echo "running PHPCS!"
  deploy:
    docker:
      - image: circleci/php:7.2-node
    steps:
      - checkout
      - run:
          name: 'Deploying!'
          command: echo "WE ARE GOING TO DEPLOY!"
