# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/php:7.2-node
jobs:
  build:
    executor: my-executor
    environment:
      THEME_PATH: ~/themes/my-theme-name
    steps:
      # - run:
      #     name: "Setting Up Environment Variables"
      #     command: |
      #       echo 'export THEME_PATH=~/themes/$THEME' >> $BASH_ENV
      #       echo 'export SRC_PATH=~/themes/$THEME/src' >> $BASH_ENV
      #       echo 'export COMPOSER_PATH=${THEME_PATH}/composer.json' >> $BASH_ENV
      #       echo 'export VENDOR_PATH=${THEME_PATH}/vendor' >> $BASH_ENV
      #       echo 'export PACKAGE_JSON_PATH=${THEME_PATH}/src/package.json' >> $BASH_ENV
      #       echo 'export NODE_MODULES_PATH=${THEME_PATH}/src/node_modules' >> $BASH_ENV

      - restore_cache:
          name: Restoring Source Cache
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - run: pwd && ls -la
      - checkout

      - run: pwd && ls -la

      - save_cache:
          name: Saving Source Cache
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.git

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev

      # Download and cache dependencies
      - restore_cache:
          name: Restoring Composer Cache
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "themes/my-theme-name/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: 'Install Composer dependencies'
          command: |
            cd themes/my-theme-name/
            composer install -n --prefer-dist

      - save_cache:
          name: Saving Composer Cache
          working_directory: $THEME
          key: v1-dependencies-{{ checksum "themes/my-theme-name/composer.json" }}
          paths:
            - themes/my-theme-name/vendor

      - run:
          name: 'Run PHPCS'
          command: |
            cd themes/my-theme-name/
            vendor/bin/phpcs --standard=WordPress-VIP-Go -sp --basepath=. --ignore=vendor *

      - restore_cache:
          name: Restoring Node Modules Cache
          keys:
            - node-v1-{{ checksum "themes/my-theme-name/src/package.json" }}
            - node-v1-

      - run:
          name: 'Install npm packages'
          command: |
            cd themes/my-theme-name/src
            npm install

      - save_cache:
          name: Saving Node Modules Cache
          key: node-v1-{{ checksum "~/themes/my-theme-name/src/package.json" }}
          paths:
            - themes/my-theme-name/src/node_modules

      - run:
          name: 'Build'
          command: |
            cd themes/my-theme-name/src
            npm run prod
  deploy:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-node-browsers
    steps:
      - run:
          name: Deploy Over SFTP
          command: |
            if [ "${CIRCLE_BRANCH}" = "develop" ]
            then
              echo 'export FTP_USERNAME=$FTP_USERNAME_DEV' >> $BASH_ENV
              echo 'export FTP_PASSWORD=$FTP_PASSWORD_DEV' >> $BASH_ENV
              echo 'export FTP_HOST=$FTP_HOST_DEV' >> $BASH_ENV
              echo 'export FTP_PORT=$FTP_PORT_DEV' >> $BASH_ENV
              echo 'export FTP_REMOTE_ROOT=$FTP_REMOTE_ROOT_DEV' >> $BASH_ENV
            fi
            node .circleci/deploy.js
            echo "We are online!"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
